### ISSUE TITLE
Opacity setting seems to not have any effect

### ISSUE THREAD

**Issue by danielgafni** [dima74/intellij-indent-rainbow#13]
The title. I can provide screenshots if needed, but basically the opacity is just always the same (default) for me even if i change it.

**Comment by dima74** [comment]
@danielgafni thanks for reporting! Could you please provide plugin version, IntelliJ version (Help / About / Copy) and your what is operation system

**Comment by danielgafni** [comment]
```
PyCharm 2020.1 (Professional Edition)
Build #PY-201.6668.115, built on April 7, 2020
Licensed to Daniel Gafni
Subscription is active until September 19, 2020
For educational use only.
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.7.0-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1434M
Cores: 8
Non-Bundled Plugins: com.andrey4623.rainbowcsv, com.arcticicestudio.nord.jetbrains, mobi.hsz.idea.gitignore, indent-rainbow.indent-rainbow, BashSupport, izhangzhihao.rainbow.brackets
Current Desktop: KDE
```
Plugin version - 6.3

**Comment by dima74** [comment]
@danielgafni thanks! Could you please also provide screenshot? Also I am not sure about plugin version, [latest IndentRainbow plugin version is 1.4.2](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions) and [6.3 is latest version of RainbowBrackets](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions) (it is another plugin)

By the way here is what is expected result when changing opacity:

Default
![image](https://user-images.githubusercontent.com/6505554/81061610-17bf6000-8eee-11ea-88e2-b4ed416b99dd.png)

Slightly increased
![image](https://user-images.githubusercontent.com/6505554/81061663-30c81100-8eee-11ea-956b-6bb1e7b94c2f.png)

Highly increased
![image](https://user-images.githubusercontent.com/6505554/81061864-87354f80-8eee-11ea-92ed-eb44b4de738e.png)

**Comment by danielgafni** [comment]
Yeah sorry, I indeed accidentally gave you the Rainbow Brackets version.
Indent Rainbow version is 1.4.2
Here are the screenshots. I've been restarting PyCharm in between taking them just to make sure the setting is being loaded. I've also tried setting the color to white - same outcome.

![Screenshot_20200507_165845](https://user-images.githubusercontent.com/49863538/81303974-183e2f00-9085-11ea-9305-05f8a29eb41e.png)
![Screenshot_20200507_170225](https://user-images.githubusercontent.com/49863538/81303993-1d9b7980-9085-11ea-9c76-2b107ec708b7.png)
![Screenshot_20200507_170339](https://user-images.githubusercontent.com/49863538/81304004-212f0080-9085-11ea-86c6-a314817b7e42.png)

**Comment by dima74** [comment]
@danielgafni sorry for so long response. Could you please:
* update to the latest version (1.5.1), where I added more logging
* change opacity multiplier
* send me your [idea.log file](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by danielgafni** [comment]
It is working now. Thanks!
