### ISSUE TITLE
dart可否优化啊

### ISSUE THREAD

**Issue by qingweiSun** [dima74/intellij-indent-rainbow#15]
![image](https://user-images.githubusercontent.com/16513906/82655458-cb498380-9c54-11ea-96e6-1ff3b0f5fe60.png)

**Comment by dima74** [comment]
@qingweiSun thanks for report! Could you please provide full file?

---

Also here is relevant excerpt from [FAQ](https://github.com/dima74/intellij-indent-rainbow#faq):

> **Q:** Why indent is highlighted in red?  
> **A:** Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options: 
> 
> 1) [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
> 2) [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
> 3) Enable checkbox "Never highlight indent as error" in settings
> 4) Use "simple highlighter" (not recommended)

Please let me know whether it helps. Thanks!

**Comment by qingweiSun** [comment]
1：Invalid reformat
2：Use "simple highlighter" (not recommended)
