### ISSUE TITLE
Indents don't appear on multiline comments or doc blocks

### ISSUE THREAD

**Issue by Veraxus** [dima74/intellij-indent-rainbow#17]
In PHP, indents are not applied to multiline comments beyond the first line. See attached screenshot.

![image](https://user-images.githubusercontent.com/587527/83825901-70ba1980-a68f-11ea-8be4-0c00289cdc0b.png)

**Comment by dima74** [comment]
@Veraxus thanks for the report! I already fixed this, will make new release soon

**Comment by dima74** [comment]
@Veraxus fixed in version 1.5.0!

![image](https://user-images.githubusercontent.com/6505554/84026535-f0edc100-a9a6-11ea-8096-4eea60ab09d3.png)
