### ISSUE TITLE
[Enhancement] configurable count of indentation level colors

### ISSUE THREAD

**Issue by PashaWNN** [dima74/intellij-indent-rainbow#21]
Make indentation colors configurable. In particular, I do want to see real rainbow with seven colors.

**Comment by PashaWNN** [comment]
Sorry, I see instruction in README

**Comment by PashaWNN** [comment]
I see there's only four levels of indentation. It would be great to be able to set custom count of colors. For example, 7.

**Comment by dima74** [comment]
@PashaWNN thanks for the suggestion! Please try out this plugin build: [indent-rainbow-1.6-dev.zip](https://github.com/dima74/intellij-indent-rainbow/files/5146945/indent-rainbow-1.6-dev.zip), where I added [an option to choose color palette in settings](https://user-images.githubusercontent.com/6505554/91661297-94f18f00-eaf4-11ea-9d8e-0a97ba7ae982.png). There is new `pastel` palette with 6 colors, and also you can configure custom palette with any number of colors you want!

**Comment by dima74** [comment]
Version 1.6 [was published to plugin marketplace](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/96391), feel free to provide feedback and request any other features!
