### ISSUE TITLE
Configurable file types

### ISSUE THREAD

**Issue by keeganwitt** [dima74/intellij-indent-rainbow#22]
It'd be cool if you could specify what file types the plugin should work on, the way you can in the VS Code [plugin](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow).  I like to have things like Python and YAML highlighted, but not other types.

**Comment by dima74** [comment]
@keeganwitt thanks for the suggestion! Please try out this plugin build: [indent-rainbow-1.6-dev.zip](https://github.com/dima74/intellij-indent-rainbow/files/5146945/indent-rainbow-1.6-dev.zip), where I added [an option to choose specific file types plugin should work on](https://user-images.githubusercontent.com/6505554/91661523-10a00b80-eaf6-11ea-9227-d5b42280a8c2.png). You can use this pattern: `*.py; *.yaml`

**Comment by keeganwitt** [comment]
Thanks for this!  I tried it out and it seems to be working as expected.

**Comment by dima74** [comment]
Version 1.6 [was published to plugin marketplace](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/96391), thanks for your feedback!
