### ISSUE TITLE
Add a toggle to show only inorrect indentation

### ISSUE THREAD

**Issue by krzyk** [dima74/intellij-indent-rainbow#23]
Great plugin, but I use it mostly to get the color for incorrect indentation.

So I would suggest to add a toggle that would disable the normal coloring mode and enable just the incorrect indentation.
I know I can change the colors in settings and visually disable all other colorings but it won't save the added CPU usage of this plugin (e.g. when I scroll down a  large file I can see how it slowly draws the rainbow indentation colors) hence the idea to have just a simple version with just the incorrect indent.

**Comment by dima74** [comment]
@krzyk thank you for the suggestion! Please update the plugin to [version 1.6.1](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/101424), where the option was added:

![image](https://user-images.githubusercontent.com/6505554/98372971-9c329d00-204f-11eb-91f4-5d2659fc273e.png)

**Comment by krzyk** [comment]
Thank you :)
