### ISSUE TITLE
Feature request: disable on big files

### ISSUE THREAD

**Issue by ggalmazor** [dima74/intellij-indent-rainbow#25]
## Expected Behavior

Overall IDE performance is negatively affected by this plugin when dealing with big files (hundreds of lines). 

I would like to configure a threshold of lines so that, when the file I'm editing has more lines than those set on the threshold, then this plugin is automatically disabled for that file.

That way, I can set a threshold that works for my specific environment (memory settings, type of files I open, number of open files, etc).

## Current Behavior

The plugin works for every open file, regardless of their size.

## Possible Solution

I'm not sure about the specific implementation of this feature, but I think it would require a new configuration option to enable this feature, and another new configuration field to set the threshold.

## Your Environment

* Plugin version: 1.6.1
* macOS BigSur 11.1

```
RubyMine 2020.3
Build #RM-203.5981.152, built on November 30, 2020
Licensed to Guillermo Gutierrez Almazor
Subscription is active until February 20, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: ide.balloon.shadow.size=0, jest.test.tree.use.jasmine.reporter=false
Non-Bundled Plugins: com.4lex4.intellij.solarized, com.github.mturlo.intellij.theme.spacegray, com.samdark.intellij-visual-studio-code-dark-plus, com.thvardhan.gradianto, NodeJS, org.jetbrains.plugins.vue, com.dmarcotte.handlebars, ru.adelf.idea.dotenv, indent-rainbow.indent-rainbow
```

**Comment by markuszeller** [comment]
When this plugin is active and I am running inspections for example on a Wordpress theme, it slows it extremely down - that much that it feels like a total freeze.

- Plugin version: 1.6.1
- PhpStorm 2020.3.3
- Windows 10 Build 19042

**Comment by dima74** [comment]
@ggalmazor Thanks for your feedback! The option was added in the latest release [1.7.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/146226):

![image](https://user-images.githubusercontent.com/6505554/142607826-baa78611-4dab-483a-8cac-7531d78b1412.png)
