### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by kst83** [dima74/intellij-indent-rainbow#26]
I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by dima74** [comment]
Thanks for interest in the plugin!

The plugin itself doesn't collect any information. Actually we even don't have any server or something where this information can be stored.

But we use [Sentry](https://sentry.io/) for error reporting. When some exception occurs in the plugin, IntelliJ offers user to send error report, which includes exception stacktrace, plugin version, IDE version, and some other technical information. Please note that plugin sent this information **only after explicit confirmation from user**.

So if you don't send error reports, then nothing is collected.
