### ISSUE TITLE
Performance problem with large XML files

### ISSUE THREAD

**Issue by foto-andreas** [dima74/intellij-indent-rainbow#27]
Hi,

I am facing a performance problem when viewing large xml files - without doing anything in the editor

See here: https://youtrack.jetbrains.com/issue/IDEA-268838

I reported it as IJ bug.

Andreas

**Comment by dima74** [comment]
@foto-andreas Thanks for your feedback. We definitely need to improve the performance of the plugin. For now an option to disable Indent Rainbow in big files was added:

![image](https://user-images.githubusercontent.com/6505554/142607826-baa78611-4dab-483a-8cac-7531d78b1412.png)

**Comment by dima74** [comment]
Fixed in [v2.0.1](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/161785)
