### ISSUE TITLE
Has Indent Rainbow Plugin version for Sublime Text ?

### ISSUE THREAD

**Issue by livem** [dima74/intellij-indent-rainbow#29]
Indent Rainbow was greatest helpful for the coder.
Has any version for [Sublime Text](https://www.sublimetext.com/) 3 or 4 ? Or any plan?
Thanks.

**Comment by dima74** [comment]
Sorry, I am aware only of [VSCode version](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow). I personally don't know how to develop plugins for Sublime Text, so no plans either

**Comment by livem** [comment]
Thanks for reply

**Comment by livem** [comment]
> Sorry, I am aware only of [VSCode version](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow). I personally don't know how to develop plugins for Sublime Text, so no plans either

Thanks for reply.
