### ISSUE TITLE
Configurable Colors

### ISSUE THREAD

**Issue by evliu** [dima74/intellij-indent-rainbow#3]
Thanks for this plugin; it's great. My main issue is that the colors are hard to see against my IDE background; is there a way to configure the colors so I can make then a little lighter or less opacity? Thanks!

**Comment by dima74** [comment]
@evliu Yes, I added options to change colors in latest release (1.2.0). Instructions are in [README](https://github.com/dima74/intellij-indent-rainbow#change-colors). Could you please try it out

**Comment by evliu** [comment]
Perfect! Thanks!!!

**Comment by dima74** [comment]
Thank you for reporting and feel free to ask any questions or submit feature requests!
