### ISSUE TITLE
Do not update color scheme when not needed

### ISSUE THREAD

**Issue by trustin** [dima74/intellij-indent-rainbow#31]
I'm storing my IntelliJ IDEA settings in a Git repository using the [settings repository feature](https://www.jetbrains.com/help/idea/settings-tools-settings-repository.html). It will push any configuration changes, including color scheme settings, when IntelliJ IDEA exits. If nothing was changed, it will not push any commit to the settings repository.

The problem is, `intellij-indent-rainbow` plugin keeps updating the color scheme at every launch, resulting in the change like the following:

![image](https://user-images.githubusercontent.com/173918/122968535-9a430180-d3c6-11eb-9542-9e5177a48b75.png)

As you see from the above image, `intellij-indent-rainbow` plugin doesn't really update anything. It just makes IntelliJ IDEA to update the timestamp value of the color scheme settings.

It'd be really nice if this plugin doesn't try to update anything if the current color scheme matches with the plugin's settings.

**Comment by dima74** [comment]
@trustin Thanks for your feedback! This should be fixed in the latest release [1.7.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/146226)
