### ISSUE TITLE
[TypeScript] Method parameter destructuring

### ISSUE THREAD

**Issue by t-ricci-delta** [dima74/intellij-indent-rainbow#33]
Intent rainbow does not seem to like when I destructure typed parameters on methods in TypeScript

![image](https://user-images.githubusercontent.com/87062919/139865500-928a8063-8b1c-4e36-9190-8969255aa03c.png)

The indentation is configured as two spaces, and you can see a bright red background if **any** space is added at the start of the line after the open brackets and before the closing brackets {}

This is verified in Rider on windows 10, but I remember it happening in macOS and other jetbrains products as well

**Comment by dima74** [comment]
@t-ricci-delta thanks for report!

Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options: 

1) [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
2) [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
3) Enable checkbox "Never highlight indent as error" in settings
4) Use "simple highlighter" (not recommended)

**Comment by t-ricci-delta** [comment]
> @t-ricci-delta thanks for report!
> 
> Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options:
> 
> 1. [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
> 2. [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
> 3. Enable checkbox "Never highlight indent as error" in settings
> 4. Use "simple highlighter" (not recommended)

I tried to run "Reformat Code" but the coding style remained the same. Also I'm using the Prettier extension as well:
https://plugins.jetbrains.com/plugin/10456-prettier

**Comment by t-ricci-delta** [comment]
> @t-ricci-delta thanks for report!
> 
> Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options:
> 
> 1. [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
> 2. [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
> 3. Enable checkbox "Never highlight indent as error" in settings
> 4. Use "simple highlighter" (not recommended)

Regarding point 2. I haven't found any option to allow to indent if the parameter destructuring is carried over multiple lines instead of in the same line

**Comment by dima74** [comment]
Looks like the only option is to use "simple highlighter", since non-default formatter is used (Prettier)

**Comment by t-ricci-delta** [comment]
Seems a problem of the default formatter for typescript (I disabled Prettier), this is what formatting the code looked like (ugly alignment of destructured parameter)

![image](https://user-images.githubusercontent.com/87062919/139872778-77f105f3-acef-4562-a528-6d03454ed4d4.png)

I'm still tinkering with the default code style to find out which option is behaving like that exactly

**Comment by t-ricci-delta** [comment]
The error color to me was useful if the number of spaces was not even (multiple of configured tab width), but it's not what the plugin implementation is checking, if it relies on the formatter

**Comment by dima74** [comment]
> The error color to me was useful if the number of spaces was not even (multiple of configured tab width)

This is exactly how simple highlighter works, if I remember correctly

**Comment by t-ricci-delta** [comment]
> > The error color to me was useful if the number of spaces was not even (multiple of configured tab width)
> 
> This is exactly how simple highlighter works, if I remember correctly

Then I'll stick to it since for js/ts using Prettier is far more useful. It would be a nice to have the possibility to have the other languages (C#/Java) show the spacing from the default formatter though.

For now I'm content with the "simple highligher option" since I only care if there are mixed tabs/spaces or uneven number of spaces

**Comment by dima74** [comment]
> It would be a nice to have the possibility to have the other languages (C#/Java) show the spacing from the default formatter though.

The option to use different highlighters for different languages was added in the latest release [1.7.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/146226):

![image](https://user-images.githubusercontent.com/6505554/142608663-94bd5ed8-6a00-4571-9f32-db09bec3f5a5.png)
