### ISSUE TITLE
Plugin consider loop codes after a label in JavaScript as error indent

### ISSUE THREAD

**Issue by xsjcTony** [dima74/intellij-indent-rainbow#37]
Hi, I found another bug regarding the label in JavaScript:

![image](https://user-images.githubusercontent.com/45784210/143722025-53a10ba8-c6b2-4854-9a4c-2f123ef49779.png)

All lines of the loop after a label is considered to be an error but it's actually not.
My IDE version is PhpStorm 2021.2.3.

Thanks

**Comment by dima74** [comment]
Hi! Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options: 

1) [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
2) [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
3) Enable checkbox "Never highlight indent as error" in settings
4) Use ["Simple highlighter"](https://raw.githubusercontent.com/dima74/intellij-indent-rainbow/master/assets/choose-simple-annotator.png)

**Comment by xsjcTony** [comment]
I changed the code style settings in IDE and everything works well. Thanks a lot!

> Hi! Plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options:
> 
> 1. [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
> 2. [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
> 3. Enable checkbox "Never highlight indent as error" in settings
> 4. Use ["Simple highlighter"](https://raw.githubusercontent.com/dima74/intellij-indent-rainbow/master/assets/choose-simple-annotator.png)
