### ISSUE TITLE
log4j issue

### ISSUE THREAD

**Issue by sascha-andres** [dima74/intellij-indent-rainbow#38]
At my company all machines are scanned for software "containing" the log4j vulnerability. This plugin is highlighted because it is using sentry in version 1.7.30.

Is there any update planned with a newer sentry version?

**Comment by dima74** [comment]
I checked the plugin jar and don't find the `log4j` library:
![image](https://user-images.githubusercontent.com/6505554/146191708-105a9a56-a1ce-4278-b5e3-b825143b604d.png)
Actually we [exclude log dependency from sentry](https://github.com/dima74/intellij-indent-rainbow/blob/70ec121f87d3a1e176cdcb20bd317e7fe947785b/build.gradle.kts#L28).

Btw sentry dependency will be removed in the next release.

**Comment by sascha-andres** [comment]
I assume it is inside the sentry jar file, but this information helped a lot.
