### ISSUE TITLE
Code inside (...) treated as one line

### ISSUE THREAD

**Issue by gogainda** [dima74/intellij-indent-rainbow#40]
Idea
<img width="734" alt="Screenshot 2022-01-19 at 15 45 42" src="https://user-images.githubusercontent.com/379758/150154367-451eb039-db75-4e9c-afe8-bbc271fa9c61.png">

VSCode 
<img width="423" alt="Screenshot 2022-01-19 at 15 49 07" src="https://user-images.githubusercontent.com/379758/150154540-4cd3365f-f6c8-48a7-83b8-5c58d0db1317.png">

**Comment by dima74** [comment]
@gogainda Hi! Please try to use simple highlighter:
![](https://raw.githubusercontent.com/dima74/intellij-indent-rainbow/master/assets/choose-simple-annotator.png)

**Comment by dima74** [comment]
@gogainda should be fixed in latest release [`2.0.2`](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/162919). Please feel free to reopen if you encounter any problems
