### ISSUE TITLE
Severe logspam due to calling a deprecated method

### ISSUE THREAD

**Issue by HonoluluHenk** [dima74/intellij-indent-rainbow#41]
The plugin creates a massive amount of logspam in the system log (syslog) because it seems to be calling a deprecated method.

This error was reported 21260 times in just 2-3 hours.

I'm using linux, not sure if other OS are affected. This might possibly be the case since the error refers to some IntelliJ-Plugin-API.

Log-Entry:
```Feb  4 13:05:38 my-hostname jetbrains-idea.desktop[7792]: 2022-02-04 13:05:38,200 [11086275]   WARN - emon.impl.AnnotationHolderImpl - Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class indent.rainbow.IrAnnotatorImpl) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: indent-rainbow.indent-rainbow]' was reported 21260 times```

**Comment by akmalick** [comment]
I can confirm this. I am on a Windows 10 System.
Looking at the log for past 2 hours, in my case it was reported **9480** times :

`Exception 'com.intellij.diagnostic.PluginException: 'AnnotationHolder.createInfoAnnotation()' method (the call to which was found in class indent.rainbow.IrAnnotatorImpl) is slow, non-incremental and thus can cause unexpected behaviour (e.g. annoying blinking), is deprecated and will be removed soon. Please use `newAnnotation().create()` instead [Plugin: indent-rainbow.indent-rainbow]' was reported 9480 times
`
The plugin is too slow. Yesterday I opened a json file with about 1K lines and I couldn't see the indentation markers until a couple of seconds passed. Also, when I scrolled through the file I could literally see the lagging.

**Comment by dima74** [comment]
@HonoluluHenk @akmalick @robp94 Could you please try this version of the plugin and check whether issue was fixed: 

[Indent Rainbow-2.0.0.zip](https://github.com/dima74/intellij-indent-rainbow/files/8090613/Indent.Rainbow-2.0.0.zip)

**Comment by HonoluluHenk** [comment]
works for me, too.

Thanks a lot!

**Comment by dima74** [comment]
Fixed in [v2.0.1](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions/stable/161785)
