### ISSUE TITLE
Custom color scheme not working

### ISSUE THREAD

**Issue by ekatz-quotient** [dima74/intellij-indent-rainbow#45]
Hi,
I used to disable the red error indent from "Color Scheme > Indent Rainbow" but it doesn't work with the new highlighter.
With the old one ("Use formatter highlighter in these files") it still works, but this highlighter doesn't work on empty lines, which makes it not as good.
It would be nice if the "Color Scheme" settings could work with the default highlighter.
Thank you for this great plugin.

**Comment by dima74** [comment]
Hi @ekatz-quotient! Sorry for the long response

If you want to disable red color, please use option `Never highlight indent as error` in advanced settings:

![image](https://user-images.githubusercontent.com/6505554/171837462-06cecbc9-9dea-40fc-bf1d-8181c008a51e.png)

Also please note that for new highlighter, custom color sheme should be configured in [Indent rainbow settings](https://user-images.githubusercontent.com/6505554/171838818-cff9108d-830e-47db-b69c-f745445227ff.png). Configuration in `Editor | Color Scheme` is for old highlighter and will be removed in future release

**Comment by ekatz-quotient** [comment]
Cool, it would be great if the caption indicated that `*` is an option.
