### ISSUE TITLE
Incapable of installing

### ISSUE THREAD

**Issue by Gideon-Felt** [dima74/intellij-indent-rainbow#46]
2022.0.1 - 2022.1.1
Click the install button from the plugins page and nothing happens, after numerous restarts of Pycharm, it shows as uninstalled each time I return to the plugins section in settings.

**Comment by voom** [comment]
Plugin is not yet compatible with version 2022. I can take it and update compatibility platform.

**Comment by dima74** [comment]
Hi @Gideon-Felt! Unfortunately, I can't reproduce this issue. Could you please provide some details - at least your OS, exact version of PyCharm (Community/Professional, etc) and [`idea.log`](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)

**Comment by Gideon-Felt** [comment]
I've come back to this a few days later. When trying to install the plugin, I was actually given a helpful prompt this time, saying I didn't have permission, So I restarted the IDE with administrative permissions, and it was installed and remained installed and visually changed the editor. So I'm guessing this was some IntelliJ issue not your plugin's issue.

**Comment by Gideon-Felt** [comment]
Also for reference:
* Windows 11 (This alone can be an issue)
* 2022.1.2 CE

I'll leave the `idea.log` out since this resolved itself anyways.
