### ISSUE TITLE
"Indent rainbow now shows on empty lines" feature has no option to disable it

### ISSUE THREAD

**Issue by ducktordanny** [dima74/intellij-indent-rainbow#48]
I loved how it was before and I don't really understand why it was necessary to change. It would be great if we would have a settings option where we could choose whether we want it to be shown on an empty line whether not.

**Comment by dima74** [comment]
Hi @ducktordanny! There is such option:

![image](https://user-images.githubusercontent.com/6505554/180612376-e340ae78-97ea-465d-9390-4373ae0b445e.png)

**Comment by ducktordanny** [comment]
Oh nice, it seems I jumped over that options, thanks for clearing it out. :)
