### ISSUE TITLE
ide freeze with file has many lines

### ISSUE THREAD

**Issue by bluelovers** [dima74/intellij-indent-rainbow#5]
https://youtrack.jetbrains.com/issue/IDEA-232747

video
[bandicam 2020-02-12 10-22-42-592.zip](https://github.com/dima74/intellij-indent-rainbow/files/4191229/bandicam.2020-02-12.10-22-42-592.zip)

**Comment by dima74** [comment]
@bluelovers could you please update to latest version (1.4) and test performance? I made highlighting incremental in version 1.4, so it should be much faster now, especially on large files

**Comment by dima74** [comment]
Closing as resolved. Please feel free to reopen if you still encounter performance issues!
