### ISSUE TITLE
please restore `Never highlight indent as error(in red color)`

### ISSUE THREAD

**Issue by trydofor** [dima74/intellij-indent-rainbow#51]
I remember the previous version, there is an option to disable the ERROR color to show

there are almost some wrapped long lines, eg. long parameter, long expression, which aligns to the top level. and `intellij-indent-rainbow` mark these line as ERROR indent.

the (Red) ERROR color makes me nervous :)
please restore the option.

**Comment by trydofor** [comment]
Never highlight indent as error(in red color)
version 1.7.0

**Comment by dima74** [comment]
Hi @trydofor! It is still possible, just use "Never highlight indent as error for languages" settings (specify `*` to disable error highlighting in all files)

![](https://user-images.githubusercontent.com/6505554/189267368-6f492cac-d5d0-4e69-a394-063b976d384d.png)

**Comment by trydofor** [comment]
thanks, I never think about this options.
I downgrade to 1.7.0 and upgrade back now 😃
