### ISSUE TITLE
Feature request: add a toggle to disable highlight incorrect indentation

### ISSUE THREAD

**Issue by OctoSheep** [dima74/intellij-indent-rainbow#56]
I format my code often, so I rarely have problems with incorrect indentation, but longer lines of code may be truncated, resulting in incorrectly indented. So is it possible to add an option to disable it?

![图片](https://user-images.githubusercontent.com/30658014/222420490-4b642ca1-42ce-4f4a-aaf2-a08ea0022b6f.png)

**Comment by dima74** [comment]
Hi @OctoSheep! It is already possible, please see https://github.com/dima74/intellij-indent-rainbow/issues/51#issuecomment-1241464415 for details

**Comment by OctoSheep** [comment]
Thank you for your reply!
