### ISSUE TITLE
Feature request - some kind of support for wrapped indentations

### ISSUE THREAD

**Issue by dmurat** [dima74/intellij-indent-rainbow#6]
It will be great to have some sort of support for indentations appearing because of wrapping. Currently, they are reported/colored as errors which significantly reduces usability of otherwise great plugin. 

I think it will be enough to allow the option to not color as error indentations which are by grater than the base indentation width by some multiplier.

Tnx.

**Comment by dima74** [comment]
@dmurat thank you for request. Could you please provide screenshot which illustrates the problem?

**Comment by dmurat** [comment]
Sure, here it is.
![Screenshot 2020-02-18 at 19 17 17](https://user-images.githubusercontent.com/470930/74765208-6bbd8f80-5283-11ea-949e-b18099a5e7d8.png)

**Comment by dima74** [comment]
@dmurat plugin highlights indent in red based on default IntelliJ formatter. If some line is highlighted in red, it means that after "Reformat Code" action this line indent will be changed. So you have four options: 

1) [Reformat your code](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html)
2) [Configure your code style](https://www.jetbrains.com/help/idea/configuring-code-style.html)
3) Enable checkbox "Never highlight indent as error" in settings
4) Use "simple highlighter" (not recommended)

Option "Never highlight indent as error" was added in [version 1.4](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/versions)

**Comment by dima74** [comment]
Closing as answered. Please feel free to reopen if you still have questions!
