### ISSUE TITLE
Add "Transparent"/"Opaque" for scope highlighting

### ISSUE THREAD

**Issue by ZipBrandon** [dima74/intellij-indent-rainbow#60]
Scope highlighting is working great but sometimes it is a little intense. I would like to back off the intensity via opacity like indentation highlighting.

**Comment by dima74** [comment]
Hi @ZipBrandon! Could you please provide a screenshot? I don't fully understand what is scope highlighting

**Comment by ZipBrandon** [comment]
Sure!

![image](https://github.com/dima74/intellij-indent-rainbow/assets/68867795/6335b5f9-3a06-4e95-98ab-b00d29dd4695)


![image](https://github.com/dima74/intellij-indent-rainbow/assets/68867795/7a9a8290-1dec-4a64-8b46-738ef2003f97)

**Comment by ZipBrandon** [comment]
I see this is managed on Rainbow Brackets! Sorry!

**Comment by dima74** [comment]
Alright, I see you opened an issue for Rainbow Brackets, so let's close this issue. Feel free to open a new one if you have any other problems!
