### ISSUE TITLE
Not keeping up with errors / Not dynamic enough

### ISSUE THREAD

**Issue by FirstTimeInForever** [dima74/intellij-indent-rainbow#7]
Highlighting breaks on any error (e. g. when you type). It is very annoying.

![Screen-Recording-2020-02-22-at-0](https://user-images.githubusercontent.com/7830574/75072870-607b9580-5509-11ea-8951-9258919539ec.gif)

**Comment by dima74** [comment]
Fixed in [version 1.3.0](https://plugins.jetbrains.com/plugin/13308-indent-rainbow/update/79251)
